# -*- coding: utf-8 -*-
"""WEEK3 A108260074 黃進勝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ef7W3BEfVnXf-0Vk5ff4nyoOkh2Mx7AS
"""

print ("Hello world")

print("I am 黃進勝")