# -*- coding: utf-8 -*-
"""Week4-A108260074黃進勝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_J4Viv2UlPuG3wuYVIASGV4-vJwXa0Ho
"""

a=1
print(a)

name=input("請問貴姓大名? ")
print(name)

x=1
y=2
id(1)

a=1
print(a,id(a))
a='Python'
print(a,id(a))

x=1
y=1 
print(id(x),id(y))
print(x,y)

x=[1,2,3]
y=[1,2,3]
print(x is y)

